// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Csystems.Aula.Persistencia.Dados.SQLServer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CampoNovo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoNovo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031417591_CampoNovo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
